### ISSUE TITLE
Build "design principles" section

### ISSUE THREAD

**Issue by boshek** [ateucher/pkg-dev-dfo-2024-11#8]
Design principles
- messages, warnings, errors
- default argument values
- input checking
- function size / helper functions

**Comment by boshek** [comment]
Include a test here for this type of thing

**Comment by ateucher** [comment]
Use cli for "communicatin" - messages, warnings, errors.

**Comment by boshek** [comment]
Include some styling things:
- 80 character lines
- spaces around operators
- proper indentation
- newlines where appropriate
- don't be afraid of vertical spaces
